-- 权限种子数据
DELETE FROM role_permission;
DELETE FROM permission;
ALTER TABLE permission AUTO_INCREMENT = 1;

INSERT IGNORE INTO permission (id, code, name, type, parent_id, path, method, sort) VALUES
(1, 'system', '系统管理', 'MENU', 0, '/system', NULL, 1),
(2, 'system:users', '用户管理', 'MENU', 1, '/system/users', NULL, 1),
(3, 'system:users:list', '用户列表', 'API', 2, '/api/users/page', 'GET', 1),
(4, 'system:users:create', '新增用户', 'BUTTON', 2, '/api/users', 'POST', 2),
(5, 'system:users:edit', '编辑用户', 'BUTTON', 2, '/api/users', 'PUT', 3),
(6, 'system:users:delete', '删除用户', 'BUTTON', 2, '/api/users/*', 'DELETE', 4),
(7, 'system:users:roles', '分配角色', 'BUTTON', 2, '/api/users/*/roles', 'PUT', 5),
(8, 'system:roles', '角色管理', 'MENU', 1, '/system/roles', NULL, 2),
(9, 'system:roles:list', '角色列表', 'API', 8, '/api/roles/page', 'GET', 1),
(10, 'system:roles:create', '新增角色', 'BUTTON', 8, '/api/roles', 'POST', 2),
(11, 'system:roles:edit', '编辑角色', 'BUTTON', 8, '/api/roles', 'PUT', 3),
(12, 'system:roles:delete', '删除角色', 'BUTTON', 8, '/api/roles/*', 'DELETE', 4),
(13, 'system:roles:permissions', '配置权限', 'BUTTON', 8, '/api/roles/*/permissions', 'PUT', 5),
(20, 'question', '题库管理', 'MENU', 0, '/question', NULL, 2),
(21, 'question:subjects', '科目管理', 'MENU', 20, '/subjects', NULL, 1),
(22, 'question:subjects:list', '科目列表', 'API', 21, '/api/subjects/*', 'GET', 1),
(23, 'question:subjects:create', '新增科目', 'BUTTON', 21, '/api/subjects', 'POST', 2),
(24, 'question:subjects:edit', '编辑科目', 'BUTTON', 21, '/api/subjects', 'PUT', 3),
(25, 'question:subjects:delete', '删除科目', 'BUTTON', 21, '/api/subjects/*', 'DELETE', 4),
(26, 'question:list', '题目列表', 'MENU', 20, '/questions', NULL, 2),
(27, 'question:list:view', '查看题目', 'API', 26, '/api/questions/page', 'GET', 1),
(28, 'question:create', '创建题目', 'MENU', 20, '/questions/create', NULL, 3),
(29, 'question:create:do', '创建题目', 'BUTTON', 28, '/api/questions', 'POST', 1),
(40, 'paper', '试卷管理', 'MENU', 0, '/paper', NULL, 3),
(41, 'paper:list', '试卷列表', 'MENU', 40, '/papers', NULL, 1),
(42, 'paper:list:view', '查看试卷', 'API', 41, '/api/papers/page', 'GET', 1),
(43, 'paper:list:detail', '试卷详情', 'API', 41, '/api/papers/*', 'GET', 2),
(44, 'paper:create', '创建试卷', 'MENU', 40, '/papers/create', NULL, 2),
(45, 'paper:templates', '组卷模板', 'MENU', 40, '/paper-templates', NULL, 3),
(46, 'paper:templates:create', '创建模板', 'MENU', 40, '/paper-templates/create', NULL, 4),
(47, 'paper:exams', '考试安排', 'MENU', 40, '/exams', NULL, 5),
(48, 'paper:exams:list', '考试列表', 'API', 47, '/api/exams/page', 'GET', 1),
(49, 'paper:exams:create', '创建考试', 'BUTTON', 47, '/api/exams', 'POST', 2),
(50, 'paper:exams:publish', '发布考试', 'BUTTON', 47, '/api/exams/*/status', 'PUT', 3),
(51, 'paper:my-exams', '我的考试', 'MENU', 40, '/my-exams', NULL, 6),
(52, 'paper:grading', '批改管理', 'MENU', 40, '/grading', NULL, 7),
(53, 'paper:grading:list', '批改列表', 'API', 52, '/api/grading/exams', 'GET', 1),
(54, 'paper:grading:grade', '批改打分', 'BUTTON', 52, '/api/grading/sessions/*/grade', 'POST', 2),
(55, 'paper:grading:release', '发布成绩', 'BUTTON', 52, '/api/grading/sessions/*/release', 'POST', 3);
